config/routes.rb
Rails.application.routes.draw do

  root to: 'days#index'

  resources :days do
    resources :attendances, only: [:create, :destroy, :show] do
      resources :flights
    end
  end

  resources :students do
    resources :gliders
    resources :additional_flights
    resources :licences
    member do
      get :flights
    end
  end

  resources :gliders

  resources :flights

end

app/models/student.rb
class Student < ApplicationRecord
  has_many :attendances, dependent: :destroy
  has_many :gliders, dependent: :destroy
  has_many :flights, through: :attendances
  has_many :additional_flights
  has_many :licences
  validates :first_name, :last_name, presence: true

  def name
    [first_name, middle_name, last_name].reject(&:blank?).join(' ')
  end

  def total_flights
    flight_count = self.flights.count
    additional_flight_count = self.additional_flights.count

    flight_count + additional_flight_count
  end

  def total_flights_until_today(today_attendance)
    today = today_attendance.day.date
    all_flights = []
    self.attendances.each do |attendance|
      if attendance.day.date < today
       all_flights << attendance.flights.count
      end
    end
    self.additional_flights.count + all_flights.sum
  end

  def all_flights
    all_flights = []
    all_flights += self.flights
    all_flights += self.additional_flights
    all_flights.sort_by(&:date).reverse #stands for { |flight| flight.date}
  end

  def count_attendances
    self.attendances.count
  end

  def has_ch_licence?
    licences.any? { |licence| licence.country == "CH" }
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    Student.create(student_params)

    redirect_to action: :index
  end

  def destroy
    student = Student.find(params[:id])

    if student.attendances.any?
      flash[:error_student_in_use] = "You can't delete this student. She or he already attended a school day.
      If you want to delete the student, please delete also the attendances."
    else
      student.destroy
    end

    redirect_to action: :index
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    Student.find(params[:id]).update(student_params)

    redirect_to action: :index
  end

  def show
    @student = Student.find(params[:id])
    @additional_flight = AdditionalFlight.new(student: @student)
    @licence = Licence.new(student: @student)
  end

  def flights
    @student = Student.find(params[:id])
  end

  private

  def student_params
    params.require(:student).permit(:first_name, :last_name, :middle_name, :additional_flights, :shv_number, :radio)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for @student do |form| %>
  <p>
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </p>

  <p>
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </p>

  <p>
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </p>

  <p>
    <%= form.label :shv_number %>
    <%= form.text_field :shv_number %>
  </p>

  <p>
    <%= form.label :radio %>
    <%= form.check_box :radio %>
  </p>

  <%= form.submit 'Create student', class: 'btn btn-success' %>
<% end %>

app/views/students/edit.html.erb
<h1>Edit student</h1>

<%= render partial: 'form' %>

app/views/students/flights.html.erb
<h1>Flights for <%= @student.name %></h1>

<div class='table-responsive'>
  <table class='table table-fit table-sm table-striped'>
    <thead class='thead-light'>
      <tr>
        <th>#</th>
        <th>Date</th>
        <th>Manoeuvres</th>
        <th>Notes</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% length = @student.all_flights.length %>
      <% @student.all_flights.each_with_index do |flight, index| %>
          <tr>
          <td><%= length - index %></td>
          <td><%= l(flight.date) %></td>
          <td><%= flight.manoeuvres %></td>
          <td><%= flight.notes %></td>
          <td><%= button_to 'Edit', edit_flight_path(flight), method: :get, class: 'btn btn-warning' %></td>
          <td><%= if flight.instance_of?(Flight)
                    button_to 'Delete', flight, method: :delete, class: 'btn btn-danger'
                  else
                    button_to 'Delete', [@student, flight], method: :delete, class: 'btn btn-danger'
                  end %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/students/index.html.erb
<h1>Students</h1>

<%= link_to 'New student', new_student_path, class: 'btn btn-primary' %>
<%= link_to 'New glider', new_glider_path, class: 'btn btn-primary' %>

<div class='table-responsive'>
  <table class='table table-striped table-sm table-fit'>
    <thead class='thead-light'>
      <tr>
        <th>Name</th>
        <th>Total flights</th>
        <th>Glider</th>
        <th>Glider color</th>
        <th>SHV Number</th>
        <th>Radio</th>
        <th>CH licence</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @students.order(:first_name).each do |student| %>
        <tr>
          <td><%= link_to student.name, student %></td>
          <td><%= student.total_flights %></td>
          <% unless student.gliders.empty? %>
            <td><%= student.gliders.last.name %></td>
            <td>
              <%= render 'gliders/glider_color', glider: student.gliders.last %>
            </td>
          <% else %>
            <td></td>
            <td></td>
          <% end %>
          <td><%= student.shv_number %></td>
          <td><%= student.radio %></td>
          <td><%= student.has_ch_licence? %></td>
          <td><%= link_to 'Edit', edit_student_path(student), class: 'btn btn-warning' %></td>
          <td><%= button_to 'Delete', student, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to 'New student', new_student_path, class: 'btn btn-primary' %>
<%= link_to 'New glider', new_glider_path, class: 'btn btn-primary' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render partial: 'form' %>

app/views/students/show.html.erb
<h1><%= @student.name %></h1>

<p>
  Total flights: <%= @student.total_flights %> =>

  <%= link_to "See flights", flights_student_path(@student) %>
</p>


<% @student.gliders.each do |glider| %>
  <p>
    Glider: <%= glider.name %>
  </p>

  <p>
    Glider color:<%= render 'gliders/glider_color', glider: glider %>
  </p>
<% end %>

<p>
  SHV Number: <%= @student.shv_number %>
</p>

<p>
  Radio: <%= @student.radio %>
</p>

<p>
  CH licence: <%= @student.has_ch_licence? %>
</p>

<%= link_to 'Back to students', students_path, class: 'btn btn-primary' %>

<h2>Create licence:</h2>

<%= render partial: 'licences/form' %>

<h2>Create additional flights:</h2>

<%= render partial: 'additional_flights/form' %>