config/routes.rb
Rails.application.routes.draw do

  root to: 'days#index'

  resources :days do
    resources :attendances, only: [:create, :destroy, :show] do
      resources :flights
    end
  end

  resources :students do
    resources :gliders
    resources :additional_flights
    resources :licences
    member do
      get :flights
    end
  end

  resources :gliders

  resources :flights

end

app/models/day.rb
class Day < ApplicationRecord
  has_many :attendances
  has_many :students, through: :attendances
  has_many :flights, through: :attendance

  def has_student?(student)
    students.include? student
  end

  def students_without_attendance
    Student.all - students
  end

  def next
    self.class.where("date > ?", date).first
  end

  def previous
    self.class.where("date < ?", date).last
  end

end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  def index
    @days = Day.all
  end

  def new
    @day = Day.new
  end

  def create
    Day.create(day_params)

    redirect_to action: :index
  end

  def destroy
    day = Day.find(params[:id])

    if day.attendances.any?
      flash[:error_day_has_attendances] = "You can't delete this day. There are students attending it.
      If you want to delete it, please delete also the attendances."
    else
      day.destroy!
    end

    redirect_to action: :index
  end

  def edit
    @day = Day.find(params[:id])
  end

  def update
    Day.find(params[:id]).update(day_params)

    redirect_to action: :index
  end

  def show
    @day = Day.find(params[:id])
    @attendance = Attendance.new(day: @day)
    @students_without_attendance = @day.students_without_attendance
    @gliders = Glider.student_gliders + Glider.school_gliders
  end

  private

  def day_params
    params.require(:day).permit(:date, :instructor, :assistant, :takeoff)
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/_form.html.erb
<%= form_for @day do |form| %>
  <p>
    <%= form.label :date %>
    <%= form.date_field :date %>
  </p>

  <p>
    <%= form.label :instructor %>
    <%= form.text_field :instructor %>
  </p>

  <p>
    <%= form.label :assistant %>
    <%= form.text_field :assistant %>
  </p>

  <p>
    <%= form.label :takeoff %>
    <%= form.text_field :takeoff %>
  </p>

  <%= form.submit 'Create/Update day', class: 'btn btn-success'%>
<% end %>

app/views/days/edit.html.erb
<h1>Edit day</h1>

<%= render partial: 'form' %>

app/views/days/index.html.erb
<h1>Days</h1>

<%= link_to 'New day', new_day_path, class: "btn btn-primary" %>

<div class='table-responsive'>
  <table class='table table-striped table-sm table-fit'>
    <thead class='thead-light'>
      <tr>
        <th>#</th>
        <th>Date</th>
        <th>Instructor</th>
        <th>Assistant</th>
        <th>Takeoff</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% days_by_year = @days.group_by {|day| day.date.year } %>
      <% days_by_year.sort_by(&:first).reverse.each do |year, days| %>
        <% days.sort_by(&:date).reverse.each.with_index do |day, index| %>
          <tr>
            <td><%= "#{days.length - index}.#{year}" %></td>
            <td><%= link_to l(day.date), day %></td>
            <td><%= day.instructor %></td>
            <td><%= day.assistant %></td>
            <td><%= day.takeoff %></td>
            <td><%= link_to 'Edit', edit_day_path(day), class: 'btn btn-warning' %></td>
            <td><%= button_to 'Delete', day, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/days/new.html.erb
<h1>New day</h1>

<%= render partial: 'form' %>

app/views/days/show.html.erb
<h1 class='d-print-none'><%= l @day.date %></h1>

<p class='d-none d-print-inline'><strong><%= l @day.date %></strong></p>

<p class='d-print-inline'>
  Instructor: <strong><%= @day.instructor %></strong>
</p>

<p class='d-print-inline'>
  Assistant: <strong><%= @day.assistant %></strong>
</p>

<p class='d-print-inline'>
  Take-off: <strong><%= @day.takeoff %></strong>
</p>

<div class='d-print-none'>
  <%= link_to 'Previous day', @day.previous, class: "btn btn-primary" %>
  <%= link_to 'Next day', @day.next, class: "btn btn-primary" %>
</div>

<hr>

<h2 class='d-print-none'>Attendances</h2>

<div class='table-responsive'>
  <table class='table table-striped table-sm table-attendances'>
    <thead class='thead-light'>
      <tr>
        <th>#</th>
        <th>Student</th>
        <th>Flights total</th>
        <th>Flights until today</th>
        <th>Glider</th>
        <th>Glider image</th>
        <th>SHV No.</th>
        <th>Flight 1</th>
        <th>Notes</th>
        <th>Flight 2</th>
        <th>Notes</th>
        <th>Flight 3</th>
        <th>Notes</th>
        <th>Flight 4</th>
        <th>Notes</th>
        <th>Flight 5</th>
        <th>Notes</th>
        <th class='d-print-none'></th>
      </tr>
    </thead>
    <tbody>
      <% @day.attendances.order(:student_id).each_with_index do |attendance, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= link_to attendance.student.name, [@day, attendance] %></td>
          <td><%= attendance.student.total_flights%></td>
          <td><%= attendance.student.total_flights_until_today(attendance)%></td>
          <td><%= attendance.glider.name%></td>
          <td>
            <%= render 'gliders/glider_color', glider: attendance.glider %>
          </td>
          <td><%= attendance.student.shv_number %></td>
          <% notes = [] %>
          <% attendance.flights.each do |flight| %>
            <td><%= flight.manoeuvres %></td>
            <td><%= flight.notes %></td>
            <% notes << flight.notes %>
          <% end %>
          <% ((5 - attendance.flights.size) * 2).times do |i| %>
            <td></td>
          <% end %>
          <td class='d-print-none'><%= button_to 'Delete', [@day, attendance], method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<hr>

<div class='d-print-none'>
  <h2>Create attendance</h2>

  <%= form_for [@day, @attendance] do |form| %>
    <%= form.hidden_field :day_id %>

    <p>
      <%= form.label :student_id %>
      <%= form.collection_select(:student_id, @students_without_attendance, :id, :name) %>
    </p>

    <p>
      <%= form.label :glider_id %>

      <%= form.select :glider_id do %>
        <% @gliders.each do |glider| %>
          <option value="<%= glider.id %>" data-student-id="<%= glider.student&.id %>"><%= glider.name %></option>
        <% end %>
      <% end %>
    </p>

    <%= form.submit 'Create an attendance', class: "btn btn-success" %>
  <% end %>

  <br>

  <%= link_to 'New day', new_day_path, class: "btn btn-primary" %>

</div>