config/routes.rb
Rails.application.routes.draw do

  root to: 'days#index'

  resources :days do
    resources :attendances, only: [:create, :destroy, :show] do
      resources :flights
    end
  end

  resources :students do
    resources :gliders
    resources :additional_flights
    resources :licences
    member do
      get :flights
    end
  end

  resources :gliders

  resources :flights

end

app/models/glider.rb
class Glider < ApplicationRecord
  COLORS = [
    'black',
    'silver',
    'blue',
    'red',
    'orange',
    'gold',
    'white'
  ]

  belongs_to :student, optional: true
  has_many :attendances

  def name
    if manufacturer.blank?
      "#{glider_type} #{size}".strip
    elsif size.blank?
      "#{glider_type} | #{manufacturer}"
    else
      "#{glider_type} #{size} | #{manufacturer}"
    end
  end

  def text_color?
    color.present?
  end

  def self.student_gliders
    where.not(student: nil)
  end

  def self.school_gliders
    where(student: nil)
  end

  def self.all_sorted_by_student_first_name
    all.sort_by { |glider| glider.student&.first_name || '' }
  end
end

app/controllers/gliders_controller.rb
class GlidersController < ApplicationController
  def index
    @gliders = Glider.all
  end

  def new
    @glider = Glider.new
  end

  def create
    Glider.create(glider_params)

    redirect_to action: :index
  end

  def destroy
    glider = Glider.find(params[:id])
    if glider.attendances.any?
      flash[:error_glider_in_use] = "You can't delete this glider. It was already used during the school day.
      If you want to delete it please delete also the attendances."
    else
      glider.destroy
    end
    redirect_to action: :index
  end

  def edit
    @glider = Glider.find(params[:id])
  end

  def update
    glider = Glider.find(params[:id])
    glider.update(glider_params)

    if params[:glider][:text_color] == 'true'
      glider.color_background = nil
      glider.color_arc = nil
      glider.color_oval = nil
    else
      glider.color = nil
    end

    glider.save!

    redirect_to action: :index
  end

  def show
    @glider = Glider.find(params[:id])

    respond_to do |format|
      format.html
      format.svg { render @glider  }
    end
  end

  private

  def glider_params
    params.require(:glider).permit(:glider_type, :size, :manufacturer, :color,
      :serial_number, :year_manufactured, :student_id, :color_background, :color_arc, :color_oval)
  end
end

app/helpers/gliders_helper.rb
module GlidersHelper
  def show_glider_svg(glider)
    File.open("app/assets/glider.svg.erb", 'rb') do |file|
      ERB.new(file.read).result_with_hash(glider: glider).html_safe
    end
  end
end

app/views/gliders/_form.html.erb
<%= form_for @glider do |form| %>

  <p>
    <%= form.label :glider_type %>
    <%= form.text_field :glider_type %>
  </p>

  <p>
    <%= form.label :size %>
    <%= form.text_field :size %>
  </p>

  <p>
    <%= form.label :manufacturer %>
    <%= form.text_field :manufacturer %>
  </p>

  <p>
    <%= form.label :serial_number %>
    <%= form.text_field :serial_number %>
  </p>

  <p>
    <%= form.label :year_manufactured %>
    <%= form.number_field :year_manufactured, min: 1990, max: 2020 %>
  </p>

  <p>
    <%= form.label :student_id %>
    <%= form.collection_select(:student_id, Student.all, :id, :name, include_blank: 'School glider') %>
  </p>

  <h3>Glider colors</h3>

  <div class="form-check">
    <%= form.radio_button :text_color?, false, class: 'form-check-input glider-color-radios', id: 'glider-color-picture-radio', data: {'visible-class': 'glider-color-select'} %>
  <label class="form-check-label" for="glider-color-picture-radio">
    Select glider colors
  </label>
  <p>
    <%= show_glider_svg @glider %>
  </p>

  <p>
    <%= form.label :color_background %>
    <%= form.select :color_background , options_for_select(Glider::COLORS, @glider.color_background),
    {include_blank: true}, class: 'glider-color-select', data: {area: 'background'} %>
  </p>

  <p>
    <%= form.label :color_arc %>
    <%= form.select :color_arc, options_for_select(Glider::COLORS, selected=@glider.color_arc),
    {include_blank: true}, class: 'glider-color-select', data: {area: 'arc'} %>
  </p>

  <p>
    <%= form.label :color_oval %>
    <%= form.select :color_oval, options_for_select(Glider::COLORS, selected=@glider.color_oval),
    {include_blank: true}, class: 'glider-color-select', data: {area: 'oval'} %>
  </p>
</div>
<div class="form-check">
  <%= form.radio_button :text_color?, true, class: 'form-check-input glider-color-radios', id: 'glider-color-text-radio', data: {'visible-class': 'glider-color-text'} %>
  <label class="form-check-label" for="glider-color-text-radio">
    Write glider colors <%= form.text_field :color, class: 'glider-color-text' %>
  </label>
</div>

  <%= form.submit class: 'btn btn-success' %>
<% end %>

app/views/gliders/_glider.svg.erb
<%= show_glider_svg @glider %>

app/views/gliders/_glider_color.html.erb
<% if glider.color.present? %>
  <%= glider.color %>
<% else %>
  <%= show_glider_svg glider %>
<% end %>

app/views/gliders/edit.html.erb
<h1>Edit glider <% if @glider.student&.name.present? %>
  from <%= @glider.student&.name %>
  <% end %></h1>

<%= render partial: 'form' %>

app/views/gliders/index.html.erb
 <h1>Gliders</h1>

<%= link_to 'New glider', new_glider_path, class: 'btn btn-primary' %>

<div class='table-responsive'>
  <table class='table table-fit table-sm table-striped'>
    <thead class='thead-light'>
      <tr>
        <th>Student</th>
        <th>Type</th>
        <th>Size</th>
        <th>Manufacturer</th>
        <th>Glider color</th>
        <th>Serial Number</th>
        <th>Year Manufactured</th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% Glider.all_sorted_by_student_first_name.each do |glider| %>
        <tr>
          <td><%= glider.student&.name %></td>
          <td><%= link_to glider.glider_type, glider %></td>
          <td><%= glider.size %></td>
          <td><%= glider.manufacturer %></td>
          <td><%= render 'gliders/glider_color', glider: glider %></td>
          <td><%= glider.serial_number %></td>
          <td><%= glider.year_manufactured %></td>
          <td><%= link_to 'Edit', edit_glider_path(glider), class: 'btn btn-warning' %></td>
          <td><%= button_to 'Delete', glider, method: :delete, confirm: 'Are you sure?', class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= link_to 'New glider', new_glider_path, class: 'btn btn-primary' %>

app/views/gliders/new.html.erb
<h1>New glider</h1>

<%= render partial: 'form' %>

app/views/gliders/show.html.erb
<h1><%= @glider.glider_type %> from <%= @glider.student&.name %></h1>

<p>
  Size: <%= @glider.size %>
</p>

<p>
  Manufacturer: <%= @glider.manufacturer %>
</p>

<p>
  Color: <%= render 'gliders/glider_color', glider: @glider %>
</p>

<p>
  Serial Number: <%= @glider.serial_number %>
</p>

<p>
  Year Manufactured: <%= @glider.year_manufactured %>
</p>

<%= link_to 'Back to gliders', gliders_path %>